kind: Service
apiVersion: v1
metadata:
# Set your user name
  name: oroosh89-hello-world
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
# Set your user name
    app: oroosh89-hello-world